FROM node:10
# Create app directory
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
#COPY package*.json /usr/src/app

RUN npm install
# If you are building your code for production
RUN npm ci --only=production

# Bundle app source
COPY . .
#COPY . /usr/src/app

#Expose port 3000
EXPOSE 3000

#Command used to start Backend Server using server.js
CMD [ "node", "server.js" ]